# Generated by Django 4.0.3 on 2022-04-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aindice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aindice', models.CharField(default='A1', max_length=200)),
                ('nombreA', models.CharField(max_length=11000)),
            ],
        ),
        migrations.CreateModel(
            name='Owasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='OWASP', max_length=200)),
                ('año', models.CharField(max_length=1000)),
                ('Aindice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aindice')),
            ],
        ),
    ]
