# Generated by Django 4.0.3 on 2022-04-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owasp',
            name='Aindice',
        ),
    ]
